"use client";
import { useEffect, useState } from "react";
function urlBase64ToUint8Array(base64String: string) { const padding = "=".repeat((4 - (base64String.length % 4)) % 4); const base64 = (base64String + padding).replace(/-/g, "+").replace(/_/g, "/"); const raw = atob(base64); return Uint8Array.from([...raw].map((c) => c.charCodeAt(0))); }
export default function ShaunDiaryNotifications() {
  const [state, setState] = useState("Checking notifications..."); const [busy, setBusy] = useState(false);
  useEffect(() => { if (!("serviceWorker" in navigator) || !("PushManager" in window)) return setState("Push notifications are not supported on this browser."); navigator.serviceWorker.register("/sw.js").then(async (r) => { const s = await r.pushManager.getSubscription(); setState(s ? "Notifications enabled" : Notification.permission === "denied" ? "Notifications blocked in browser settings" : "Notifications not enabled"); }).catch(() => setState("Service worker could not be registered.")); }, []);
  async function enable() { setBusy(true); try { const permission = await Notification.requestPermission(); if (permission !== "granted") throw new Error("Notification permission was not granted."); const reg = await navigator.serviceWorker.ready; const key = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY; if (!key) throw new Error("VAPID public key is missing."); const sub = await reg.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: urlBase64ToUint8Array(key) }); const res = await fetch("/api/shaun-diary/push/subscribe", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(sub.toJSON()) }); const json = await res.json(); if (!res.ok) throw new Error(json.error || "Could not save subscription."); setState("Notifications enabled"); } catch (e: any) { setState(e.message || "Could not enable notifications."); } finally { setBusy(false); } }
  async function test() { setBusy(true); try { const res = await fetch("/api/shaun-diary/push/test", { method: "POST" }); const json = await res.json(); if (!res.ok) throw new Error(json.error || "Test failed."); setState("Test notification sent"); } catch (e: any) { setState(e.message); } finally { setBusy(false); } }
  return <div style={{ padding: 14, borderRadius: 14, background: "rgba(255,255,255,.55)", border: "1px solid rgba(0,0,0,.1)" }}><div style={{ fontWeight: 900 }}>Mobile notifications</div><div style={{ margin: "6px 0 10px", opacity: .75 }}>{state}</div><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><button type="button" onClick={enable} disabled={busy} style={btn}>Enable notifications</button><button type="button" onClick={test} disabled={busy} style={btn}>Send test</button></div></div>;
}
const btn: React.CSSProperties = { border: 0, borderRadius: 10, padding: "10px 14px", background: "#2c6fa3", color: "white", fontWeight: 900, cursor: "pointer" };
